(() => {
'use strict';
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const state = {apiUrl:localStorage.getItem('ss_api_url')||'',token:sessionStorage.getItem('ss_token')||'',provider:localStorage.getItem('ss_provider')||'gemini',questions:[],aiCount:0,user:null};
const titles={dashboard:'Dashboard',generator:'Generator Soal AI',bank:'Bank Soal',cbt:'Ujian / CBT',reports:'Laporan',settings:'Pengaturan & Login'};
$('#year').textContent=new Date().getFullYear();
function notify(msg,type=''){const n=$('#notice');n.textContent=msg;n.className='notice'+(type?' '+type:'');n.classList.remove('hidden');}
function view(v){$$('.view').forEach(x=>x.classList.toggle('hidden',x.id!=='view-'+v));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#title').textContent=titles[v]||v;$('#sidebar').classList.remove('open');}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
$$('[data-goto]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.goto)));
$('#menu').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
const sf=$('#settingsForm');sf.elements.apiUrl.value=state.apiUrl;sf.elements.provider.value=state.provider;sf.elements.token.value=state.token;
async function api(action,payload={},method='POST'){
 if(!state.apiUrl)throw Error('Isi Apps Script Web App URL terlebih dahulu di Pengaturan.');
 const url=new URL(state.apiUrl);
 if(method==='GET'){url.searchParams.set('action',action);const r=await fetch(url);if(!r.ok)throw Error('HTTP '+r.status);return r.json();}
 const r=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token:state.token,...payload})});
 const d=await r.json();if(!r.ok||d.ok===false)throw Error(d.error||('HTTP '+r.status));return d;
}
sf.addEventListener('submit',e=>{e.preventDefault();state.apiUrl=sf.elements.apiUrl.value.trim();state.provider=sf.elements.provider.value;state.token=sf.elements.token.value.trim();localStorage.setItem('ss_api_url',state.apiUrl);localStorage.setItem('ss_provider',state.provider);if(state.token)sessionStorage.setItem('ss_token',state.token);else sessionStorage.removeItem('ss_token');notify('Pengaturan disimpan di browser ini.','success');});
$('#testConnection').addEventListener('click',async()=>{const box=$('#connectionStatus');try{const d=await api('health',{},'GET');box.textContent='Backend merespons: '+(d.service||'OK')+' · '+(d.version||'');box.className='notice success';}catch(e){box.textContent=e.message;box.className='notice error';}});
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;try{const d=await api('login',{email:f.elements.email.value.trim(),password:f.elements.password.value});if(!d.token)throw Error('Token tidak diterima dari backend.');state.token=d.token;state.user=d.user||null;sessionStorage.setItem('ss_token',d.token);sf.elements.token.value=d.token;$('#sessionLabel').textContent=state.user?state.user.name+' · '+state.user.role:'Login';$('#avatar').textContent=state.user?.name?.[0]?.toUpperCase()||'G';notify('Login berhasil.','success');await refreshQuestions();}catch(err){notify('Login gagal: '+err.message,'error');}});
$('#logout').addEventListener('click',()=>{state.token='';state.user=null;sessionStorage.removeItem('ss_token');sf.elements.token.value='';$('#sessionLabel').textContent='Belum login';notify('Token lokal dihapus. Sesi server kedaluwarsa sesuai masa berlaku.');});
$('#generatorForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,btn=$('#generateBtn');btn.disabled=true;btn.textContent='Menyusun soal…';try{const s=Object.fromEntries(new FormData(f));s.count=Number(s.count);s.provider=state.provider;const d=await api('generateQuestions',{settings:s});renderGenerated(d.questions||[]);state.aiCount+=(d.questions||[]).length;$('#statAi').textContent=state.aiCount;notify('Soal berhasil dibuat. Periksa kembali kunci dan kesesuaiannya sebelum digunakan.','success');}catch(err){notify('Generate gagal: '+err.message,'error');}finally{btn.disabled=false;btn.textContent='✦ Generate soal';}});
function renderGenerated(qs){const root=$('#generated');root.replaceChildren();if(!qs.length){root.textContent='AI belum mengembalikan soal.';return;}qs.forEach((q,i)=>{const card=document.createElement('article');card.className='question-result';const h=document.createElement('h4');h.textContent=(i+1)+'. '+(q.question||'(Teks soal kosong)');card.append(h);if(Array.isArray(q.options)){const ol=document.createElement('ol');ol.type='A';q.options.forEach(o=>{const li=document.createElement('li');li.textContent=typeof o==='string'?o:(o.text||'');ol.append(li);});card.append(ol);}if(q.answer!==undefined){const a=document.createElement('div');a.className='answer';a.textContent='Kunci jawaban: '+(typeof q.answer==='string'?q.answer:JSON.stringify(q.answer));card.append(a);}if(q.explanation){const p=document.createElement('p');p.textContent='Pembahasan: '+q.explanation;card.append(p);}const b=document.createElement('button');b.className='btn outline';b.textContent='Simpan ke bank soal';b.addEventListener('click',async()=>{try{await api('save',{table:'questions',record:q});b.textContent='Tersimpan ✓';b.disabled=true;await refreshQuestions();}catch(err){notify('Gagal menyimpan: '+err.message,'error');}});card.append(b);root.append(card);});}
async function refreshQuestions(){try{const d=await api('list',{table:'questions'});state.questions=d.records||[];$('#statQuestions').textContent=state.questions.length;renderTable();}catch(err){$('#questionTable').textContent='Tidak dapat memuat bank soal: '+err.message;}}
function renderTable(){const root=$('#questionTable'),term=$('#searchQuestions').value.toLowerCase(),rows=state.questions.filter(q=>JSON.stringify(q).toLowerCase().includes(term));root.replaceChildren();if(!rows.length){root.className='empty';root.textContent='Belum ada soal atau pencarian tidak menemukan hasil.';return;}root.className='';const t=document.createElement('table'),thead=document.createElement('thead');thead.innerHTML='<tr><th>SOAL</th><th>MAPEL</th><th>KELAS / FASE</th><th>AKSI</th></tr>';t.append(thead);const body=document.createElement('tbody');rows.forEach(q=>{const tr=document.createElement('tr');const td1=document.createElement('td');td1.textContent=q.question||'';const td2=document.createElement('td');td2.textContent=q.subject||'';const td3=document.createElement('td');td3.textContent=(q.grade||'')+' / '+(q.phase||'');const td4=document.createElement('td'),del=document.createElement('button');del.className='btn outline';del.textContent='Hapus';del.addEventListener('click',async()=>{if(!confirm('Hapus soal ini?'))return;try{await api('remove',{table:'questions',id:q.id});await refreshQuestions();notify('Soal dihapus.','success');}catch(err){notify('Gagal menghapus: '+err.message,'error');}});td4.append(del);tr.append(td1,td2,td3,td4);body.append(tr);});t.append(body);root.append(t);}
$('#reloadQuestions').addEventListener('click',refreshQuestions);$('#searchQuestions').addEventListener('input',renderTable);
$('#exportCsv').addEventListener('click',()=>{if(!state.questions.length){notify('Bank soal kosong.');return;}const cols=['id','subject','grade','phase','type','question','answer','difficulty'];const esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv=[cols.join(','),...state.questions.map(q=>cols.map(k=>esc(typeof q[k]==='object'?JSON.stringify(q[k]):q[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='SmartSoal-BankSoal.csv';a.click();URL.revokeObjectURL(url);});
if(state.token){$('#sessionLabel').textContent='Sesi tersimpan';refreshQuestions();}
})();